### ISSUE TITLE
StringIterate.csvTokensTo* methods lack support for quoted  field

### ISSUE THREAD

**Issue by ShijunK** [goldmansachs/gs-collections#5]
csv is not as simple as StringIterate.tokensToList(string, ",");, a csv parser should be able to support quoted field which means comma within double quoted field should not be treated as a delimit. 

test case:

String str = "a, b,\ "c,d\"";
Verify.assertListsEqual(FastList.newListWith("a", "b", "c,d"), StringIterate.csvTokensToList(str));

**Comment by goldmansachs** [comment]
Implementing full csv parsing is beyond the scope of GS Collections. We have deprecated the StringIterate.csv* methods since they don’t handle cases such as quoted strings, embedded commas and quotes, newlines, etc. Instead, we’d suggest using a separate library for proper csv parsing. If that library returns an array of tokens, you can use ArrayAdapter to get the MutableList API.
